#vim: set ft=ansible:
---
######################### Install Basic Packages
- name: install basic packages
  yum:
    name: "{{common_packages}}"
    state: present
  register: yumr
  until: yumr is succeeded
  retries: 10
  delay: 10
  #any_errors_fatal: true
  tags:
    - install_common_packages
