---
################################################################################
################################################################################
############ Step 006 Destroy Workshop using workshop_prefix
################################################################################
################################################################################

- name: Detect in what region the stack is
  hosts: localhost
  connection: local
  gather_facts: False
  become: no
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - when: cloud_provider == 'ec2'
      include_tasks: cloud_providers/ec2_detect_region_tasks.yml

- import_playbook: "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/destroy_env.yml"
